### ISSUE TITLE
[Bug Report] `ls` 指令未按预期运行

### ISSUE THREAD

**Issue by nullqwertyuiop** [FurryR/furryr.github.io#1]
### 问题描述

直接运行 `ls` 应返回当前目录下的所有文件，而在实际使用中则提示 `参数错误。请检查参数是否正确。`

### 复现步骤

使用 `touch` 创建名为 `file1` 的文件，运行 `ls` 返回错误

### 预期结果

使用 `touch` 直接创建文件时 `ls` 返回正确的文件列表

**Comment by FurryR** [comment]
解决:没写pwd
