### ISSUE TITLE
Shell文字与背景颜色对比度过高

### ISSUE THREAD

**Issue by K926v3C** [FurryR/furryr.github.io#4]
过高的颜色对比度易造成视觉疲劳，建议将文字颜色由`white`更改为`#F5F5F7`，背景颜色由`black`更改为`#1D1D1F`。

可增加切换颜色对比度功能，以便于[残障人士阅读页面](https://github.com/FurryR/furryr.github.io/issues/3#issuecomment-1338495886)。

**Comment by FurryR** [comment]
Duplicate of #3
